const bcrypt = require('bcryptjs');
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const db = require('./src/db');

const DEMO_USER = {
  id: 'demo-user-nadira',
  name: 'Nadira Pramesti',
  displayName: 'Nadira',
  email: 'demo@notable.local',
  password: 'demo1234',
};

const uploadsDir = path.join(__dirname, 'uploads');

const folders = [
  'Semester 6',
  'Research',
  'Personal Notes',
  'Exam Prep',
  'Projects',
  'Archive',
];

const notebooks = [
  { title: 'Human Computer Interaction', folder: 'Semester 6' },
  { title: 'Data Mining', folder: 'Semester 6' },
  { title: 'Software Engineering', folder: 'Semester 6' },
  { title: 'Research Methodology', folder: 'Research' },
  { title: 'Thesis Planning', folder: 'Research' },
  { title: 'Mobile App Design', folder: 'Projects' },
  { title: 'Database Systems', folder: 'Semester 6' },
  { title: 'Machine Learning Basics', folder: 'Exam Prep' },
  { title: 'Academic Writing', folder: 'Research' },
  { title: 'Productivity Journal', folder: 'Personal Notes' },
  { title: 'UI Inspiration', folder: 'Projects' },
  { title: 'Old Coursework', folder: 'Archive' },
];

const chapterTemplates = [
  {
    title: 'Lecture Summary',
    content: 'Key ideas, definitions, and examples collected from the latest class session. Includes points to revisit before the next discussion.',
  },
  {
    title: 'Important Concepts',
    content: 'Concept map of the topic, common misconceptions, and short explanations written in plain language for fast review.',
  },
  {
    title: 'Practice Questions',
    content: 'A set of self-check questions with notes about which parts still need stronger understanding.',
  },
  {
    title: 'References',
    content: 'Useful articles, textbook sections, papers, and lecturer notes that support this notebook topic.',
  },
];

function isoFromNow(hours) {
  return new Date(Date.now() + (hours * 60 * 60 * 1000)).toISOString();
}

const todos = [
  { title: 'Review HCI heuristic evaluation notes', deadline: isoFromNow(-4), reminderAt: isoFromNow(-28), academicWeight: 8, estimatedEffort: 4, notebook: 'Human Computer Interaction' },
  { title: 'Prepare Data Mining quiz summary', deadline: isoFromNow(-2), reminderAt: isoFromNow(-26), academicWeight: 7, estimatedEffort: 5, notebook: 'Data Mining' },
  { title: 'Draft thesis problem statement', deadline: isoFromNow(20), reminderAt: isoFromNow(-1), academicWeight: 10, estimatedEffort: 7, notebook: 'Thesis Planning' },
  { title: 'Outline thesis research questions', deadline: isoFromNow(26), reminderAt: isoFromNow(2), academicWeight: 9, estimatedEffort: 5, notebook: 'Thesis Planning' },
  { title: 'Collect thesis advisor feedback', deadline: isoFromNow(29), reminderAt: isoFromNow(3), academicWeight: 8, estimatedEffort: 4, notebook: 'Thesis Planning' },
  { title: 'Upload Software Engineering diagram', deadline: isoFromNow(30), reminderAt: isoFromNow(6), academicWeight: 6, estimatedEffort: 3, notebook: 'Software Engineering' },
  { title: 'Read two Research Methodology papers', deadline: isoFromNow(48), reminderAt: isoFromNow(24), academicWeight: 9, estimatedEffort: 6, notebook: 'Research Methodology' },
  { title: 'Revise database normalization examples', deadline: isoFromNow(57), reminderAt: isoFromNow(33), academicWeight: 8, estimatedEffort: 4, notebook: 'Database Systems' },
  { title: 'Create mobile app wireframe notes', deadline: isoFromNow(72), reminderAt: isoFromNow(48), academicWeight: 6, estimatedEffort: 5, notebook: 'Mobile App Design' },
  { title: 'Practice machine learning evaluation metrics', deadline: isoFromNow(77), reminderAt: isoFromNow(53), academicWeight: 7, estimatedEffort: 5, notebook: 'Machine Learning Basics' },
  { title: 'Clean up UI inspiration board', deadline: isoFromNow(96), reminderAt: isoFromNow(72), academicWeight: 4, estimatedEffort: 2, notebook: 'UI Inspiration' },
  { title: 'Summarize academic writing feedback', deadline: isoFromNow(101), reminderAt: isoFromNow(77), academicWeight: 5, estimatedEffort: 3, notebook: 'Academic Writing' },
  { title: 'Plan next focus block', deadline: isoFromNow(120), reminderAt: isoFromNow(96), academicWeight: 5, estimatedEffort: 2, folder: 'Personal Notes' },
  { title: 'Archive completed coursework notes', deadline: isoFromNow(129), reminderAt: isoFromNow(105), academicWeight: 3, estimatedEffort: 2, folder: 'Archive' },
];

function createUploadFile(filename, title) {
  fs.mkdirSync(uploadsDir, { recursive: true });
  const filePath = path.join(uploadsDir, filename);
  const content = [
    `${title}`,
    '',
    'Demo resource generated by the Notable seed script.',
    'Use this file to test resource download behavior in the demo account.',
  ].join('\n');
  fs.writeFileSync(filePath, content);
  return Buffer.byteLength(content);
}

function clearDemoUser() {
  const existing = db.prepare('SELECT id FROM users WHERE email = ?').get(DEMO_USER.email);
  if (!existing) return;

  const userId = existing.id;

  db.prepare(`
    DELETE FROM session_todos
    WHERE session_id IN (SELECT id FROM focus_sessions WHERE user_id = ?)
       OR todo_id IN (SELECT id FROM todos WHERE user_id = ?)
  `).run(userId, userId);
  db.prepare('DELETE FROM resources WHERE user_id = ?').run(userId);
  db.prepare('DELETE FROM notes WHERE user_id = ?').run(userId);
  db.prepare('DELETE FROM chapters WHERE user_id = ?').run(userId);
  db.prepare('DELETE FROM notebooks WHERE user_id = ?').run(userId);
  db.prepare('DELETE FROM folders WHERE user_id = ?').run(userId);
  db.prepare('DELETE FROM focus_sessions WHERE user_id = ?').run(userId);
  db.prepare('DELETE FROM todos WHERE user_id = ?').run(userId);
  db.prepare('DELETE FROM users WHERE id = ?').run(userId);

  if (fs.existsSync(uploadsDir)) {
    for (const filename of fs.readdirSync(uploadsDir)) {
      if (filename.startsWith('demo-notable-')) {
        fs.unlinkSync(path.join(uploadsDir, filename));
      }
    }
  }
}

function seedDemoUser() {
  const passwordHash = bcrypt.hashSync(DEMO_USER.password, 10);

  db.prepare(`
    INSERT INTO users (id, name, email, password_hash, display_name, role)
    VALUES (?, ?, ?, ?, ?, 'user')
  `).run(DEMO_USER.id, DEMO_USER.name, DEMO_USER.email, passwordHash, DEMO_USER.displayName);

  const folderIds = new Map();
  const notebookIds = [];
  const notebookIdsByTitle = new Map();
  const chapterIds = [];
  const todoIds = [];

  const insertFolder = db.prepare('INSERT INTO folders (id, user_id, title) VALUES (?, ?, ?)');
  const insertNotebook = db.prepare('INSERT INTO notebooks (id, user_id, folder_id, title) VALUES (?, ?, ?, ?)');
  const insertChapter = db.prepare(`
    INSERT INTO chapters (id, notebook_id, user_id, title, content, created_at, updated_at)
    VALUES (?, ?, ?, ?, ?, datetime('now', ?), datetime('now', ?))
  `);
  const insertTodo = db.prepare(`
    INSERT INTO todos (id, user_id, title, deadline, folder_id, notebook_id, academic_weight, estimated_effort, reminder_at, is_completed)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `);
  const insertNote = db.prepare(`
    INSERT INTO notes (id, user_id, todo_id, title, content)
    VALUES (?, ?, ?, ?, ?)
  `);
  const insertResource = db.prepare(`
    INSERT INTO resources (id, user_id, notebook_id, chapter_id, filename, original_name, mimetype, size)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
  `);
  const insertFocusSession = db.prepare(`
    INSERT INTO focus_sessions (id, user_id, duration_minutes, started_at, ended_at, is_completed)
    VALUES (?, ?, ?, datetime('now', ?), datetime('now', ?), ?)
  `);
  const insertSessionTodo = db.prepare(`
    INSERT INTO session_todos (id, session_id, todo_id)
    VALUES (?, ?, ?)
  `);

  folders.forEach((title, index) => {
    const id = `demo-folder-${index + 1}`;
    insertFolder.run(id, DEMO_USER.id, title);
    folderIds.set(title, id);
  });

  notebooks.forEach((notebook, index) => {
    const notebookId = `demo-notebook-${index + 1}`;
    insertNotebook.run(notebookId, DEMO_USER.id, folderIds.get(notebook.folder), notebook.title);
    notebookIds.push(notebookId);
    notebookIdsByTitle.set(notebook.title, notebookId);

    chapterTemplates.forEach((chapter, chapterIndex) => {
      const chapterId = `demo-chapter-${index + 1}-${chapterIndex + 1}`;
      insertChapter.run(
        chapterId,
        notebookId,
        DEMO_USER.id,
        chapter.title,
        `${chapter.content}\n\nNotebook context: ${notebook.title}.`,
        `-${index + chapterIndex + 1} days`,
        `-${chapterIndex} hours`,
      );
      chapterIds.push(chapterId);
    });
  });

  todos.forEach((todo, index) => {
    const todoId = `demo-todo-${index + 1}`;
    insertTodo.run(
      todoId,
      DEMO_USER.id,
      todo.title,
      todo.deadline,
      todo.folder ? folderIds.get(todo.folder) : null,
      todo.notebook ? notebookIdsByTitle.get(todo.notebook) : null,
      todo.academicWeight,
      todo.estimatedEffort,
      todo.reminderAt,
      index % 5 === 0 ? 1 : 0,
    );
    todoIds.push(todoId);
  });

  todoIds.slice(0, 8).forEach((todoId, index) => {
    insertNote.run(
      `demo-note-${index + 1}`,
      DEMO_USER.id,
      todoId,
      `Quick note ${index + 1}`,
      'Short capture from a study session. Keep it brief, actionable, and linked to the related task.',
    );
  });

  notebookIds.slice(0, 8).forEach((notebookId, index) => {
    const filename = `demo-notable-resource-${index + 1}.txt`;
    const originalName = [
      'HCI_Checklist.pdf',
      'Dataset_Sample.csv',
      'Research_Reading_List.pdf',
      'Wireframe_Notes.txt',
      'Normalization_Cheat_Sheet.pdf',
      'Evaluation_Metrics.md',
      'Writing_Feedback.docx',
      'Project_Backlog.txt',
    ][index];
    const size = createUploadFile(filename, originalName);
    insertResource.run(
      `demo-resource-${index + 1}`,
      DEMO_USER.id,
      notebookId,
      chapterIds[index * chapterTemplates.length] || null,
      filename,
      originalName,
      'text/plain',
      size,
    );
  });

  const completedSessionId = 'demo-focus-session-completed';
  insertFocusSession.run(completedSessionId, DEMO_USER.id, 50, '-2 days', '-2 days', 1);
  insertSessionTodo.run(crypto.randomUUID(), completedSessionId, todoIds[0]);
  insertSessionTodo.run(crypto.randomUUID(), completedSessionId, todoIds[1]);
}

db.transaction(() => {
  clearDemoUser();
  seedDemoUser();
})();

console.log('Demo account seeded successfully.');
console.log(`Email: ${DEMO_USER.email}`);
console.log(`Password: ${DEMO_USER.password}`);

db.close();
